{
 "title": "overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "数据源", "query": "prometheus" },
   {
    "name": "appname",
    "label": "应用名",
    "query": {
     "query": "label_values(ego_build_info{},name)"
    }
   },
   {
    "name": "version",
    "label": "环境",
    "query": {
     "query": "label_values(ego_build_info{},version)"
    }
   },
   {
    "name": "workload",
    "label": "labels.app",
    "query": {
     "query": "label_values(ego_build_info{name=~'$appname', version=~'$version'},app)"
    }
   },
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(ego_build_info{name=~'$appname', version=~'$version',app='$workload'},kubernetes_pod_name)"
    }
   },
   { "name": "summarize", "query": "2m,5m,10m" },
   {
    "name": "method",
    "label": "方法名",
    "query": {
     "query": "label_values(ego_server_handle_seconds_count{app=~'.*$appname', version=~'$version'},method)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(ego_build_info{name=~'$appname', version=~'$version'}, kubernetes_namespace)"
    }
   },
   {
    "name": "server_error_code",
    "query": "Internal Server Error,Not Implemented,Bad Gateway,Service Unavailable,Gateway Timeout,HTTP Version Not Supported,Variant Also Negotiates,Insufficient Storage,Loop Detected,Not Extended,Network Authentication Required"
   }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{kubernetes_pod_name=~\"$instance\",app=\"$workload\"})by(job)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "application.httprequests__active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "实例数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{kubernetes_pod_name=~\"$instance\",kubernetes_namespace=\"$namespace\",version=\"$version\",app=\"$workload\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "application.httprequests__active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "应用进程最大cpu",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max (\nsum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$instance\", container!=\"POD\"}) by (pod,container)\n/\n(sum(\n    kube_pod_container_resource_limits{ resource=\"cpu\", namespace=\"$namespace\", pod=~\"$instance\"}) by (pod, container))\n)"
    }
   ]
  },
  {
   "title": "应用进程最大进程驻留内存",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(process_resident_memory_bytes{kubernetes_pod_name=~\"$instance\",kubernetes_namespace=\"$namespace\",app=\"$workload\"})\n"
    }
   ]
  },
  {
   "title": "单一实例最大QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sum(irate(ego_server_handle_seconds_count{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$instance\",app=\"$workload\"}[$summarize])) by (instance))",
     "legendFormat": "{{$instance}}"
    }
   ]
  },
  {
   "title": "总 QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sum(irate(ego_server_handle_seconds_count{kubernetes_pod_name=~\"$instance\",kubernetes_namespace=\"$namespace\",app=\"$workload\"}[$summarize])) by (job)) ",
     "legendFormat": "总 QPS"
    }
   ]
  },
  {
   "title": "单一实例最大文件句柄数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(process_open_fds{kubernetes_namespace=\"$namespace\",app=\"$workload\"})by(job)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server 端可用性",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(1-(\nsum(rate(ego_server_handle_total{type=~\"unary|stream\",app=\"$workload\",kubernetes_namespace=\"$namespace\",uniform_code=~\"$server_error_code\"}[$summarize]))/(sum(rate(ego_server_started_total{type=~\"unary|stream\",app=\"$workload\",app=~\"^($workload)$\",kubernetes_namespace=\"$namespace\"}[$summarize])) OR sum(rate(ego_server_handle_total{type=~\"unary|stream\",app=\"$workload\",app=~\"^($workload)$\",kubernetes_namespace=\"$namespace\"}[$summarize])))\n),1) OR vector(1)",
     "legendFormat": "gRPC"
    },
    {
     "expr": "clamp_max(1-(\nsum(irate(ego_server_handle_total{type=\"http\",app=\"$workload\",kubernetes_namespace=\"$namespace\",uniform_code=~\"$server_error_code\"}[$summarize]))/(sum(rate(ego_server_started_total{type=~\"http\",app=\"$workload\",kubernetes_namespace=\"$namespace\"}[$summarize])) OR sum(rate(ego_server_handle_total{type=~\"http\",app=\"$workload\",app=~\"^($workload)$\",kubernetes_namespace=\"$namespace\"}[$summarize])))\n),1) OR vector(1)",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "ego_build_info{name=\"$appname\",app=\"$workload\",kubernetes_namespace=~\"$namespace\",version=\"$version\"}"
    }
   ]
  },
  {
   "title": "应用进程CPU使用率 limit（多实例）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$instance\", container!=\"POD\"}) by (pod,container)\n/\n(sum(\n    kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\", pod=~\"$instance\"}) by (pod, container))",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "应用内存信息（多实例）",
   "type": "timeseries",
   "description": "Go程序占用的常驻内存和虚拟内存容量",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{app=\"$workload\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$instance\"})by(kubernetes_pod_name)",
     "legendFormat": "memstats_alloc | {{kubernetes_pod_name}} "
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{app=\"$workload\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$instance\"})by(kubernetes_pod_name)",
     "legendFormat": "heap_inuse | {{kubernetes_pod_name}} "
    },
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{app=~\"^($workload)$\",kubernetes_pod_name=~\"$instance\"})by(kubernetes_pod_name)",
     "legendFormat": " stack_inuse | {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(go_memstats_sys_bytes{app=~\"^($workload)$\",kubernetes_pod_name=~\"$instance\"})by(kubernetes_pod_name)",
     "legendFormat": "memstats_sys | {{kubernetes_pod_name}} "
    },
    {
     "expr": "sum(process_resident_memory_bytes{app=~\"^($workload)$\",kubernetes_pod_name=~\"$podname\"})by(kubernetes_pod_name)",
     "legendFormat": "总进程驻留内存 | {{kubernetes_pod_name}}  "
    },
    {
     "expr": "sum(nodejs_heap_space_size_used_bytes{app=~\"^($workload)$\",kubernetes_pod_name=~\"$podname\"})by(kubernetes_pod_name)",
     "legendFormat": "heap_inuse | {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(go_memstats_heap_idle_bytes{app=\"$workload\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$instance\"})by(kubernetes_pod_name)",
     "legendFormat": "heap_idle | {{kubernetes_pod_name}} "
    },
    {
     "expr": "sum(go_memstats_heap_released_bytes{app=\"$workload\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$instance\"})by(kubernetes_pod_name)",
     "legendFormat": "heap_released | {{kubernetes_pod_name}} "
    }
   ]
  },
  {
   "title": "应用连接信息（多实例）",
   "type": "timeseries",
   "description": "Go程序占用连接信息",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ego_client_stats_gauge{type=\"conn_states\",app=\"$workload\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$instance\", index=\"established\",version=\"$version\"})by(name)",
     "legendFormat": "established_{{name}}"
    },
    {
     "expr": "sum(ego_client_stats_gauge{type=\"conn_states\",app=\"$workload\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$instance\", index=\"time_wait\",version=\"$version\"})by(name)",
     "legendFormat": "time_wait_{{name}}"
    }
   ]
  },
  {
   "title": "Go Goroutines（多实例）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(go_goroutines{app=\"$workload\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$instance\"})by(kubernetes_pod_name)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{kubernetes_pod_name}}",
     "measurement": "application.httprequests__active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "实例文件句柄数（多实例）",
   "type": "timeseries",
   "description": "文件句柄数",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{app=\"$workload\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC 耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(go_gc_duration_seconds{app=\"$workload\",kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$instance\"})by(kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "max by (kind) (\n    rate(\n        nodejs_gc_duration_seconds_sum{kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$instance\"}[1m]) \n        / rate(nodejs_gc_duration_seconds_count{kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$instance\"}[1m])\n)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "服务端", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "HTTP 服务端错误码分布",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ego_server_handle_total{type=\"http\",app=\"$workload\",kubernetes_namespace=\"$namespace\"}[$summarize]))by(uniform_code,method)",
     "legendFormat": "{{uniform_code}} | {{method}}"
    }
   ]
  },
  {
   "title": "HTTP 服务端QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ego_server_handle_seconds_count{type=\"http\",app=\"$workload\",kubernetes_namespace=\"$namespace\"}[$summarize]))by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP 服务端 P99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99,irate(ego_server_handle_seconds_bucket{type=\"http\",app=\"$workload\",kubernetes_namespace=\"$namespace\"}[$summarize])>0)*1000)by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC 服务端异常状态码",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ego_server_handle_total{type=\"unary\",app=\"$workload\",kubernetes_namespace=\"$namespace\",uniform_code=~\"5.*\"}[$summarize]))by(uniform_code,method,instance)",
     "legendFormat": "{{uniform_code}} | {{method}} "
    }
   ]
  },
  {
   "title": "gRPC 服务端 QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(ego_server_handle_total{type=~\"unary|stream\",app=\"$workload\",kubernetes_namespace=\"$namespace\"}[$summarize]))by(method)",
     "legendFormat": " {{method}}"
    }
   ]
  },
  {
   "title": "gRPC 服务端 P99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99,irate(ego_server_handle_seconds_bucket{type=~\"unary|stream\",app=\"$workload\",kubernetes_namespace=\"$namespace\"}[$summarize])>0)*1000)by(method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "客户端", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "gRPC 客户端错误码分布",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ego_client_handle_total{type=\"unary\",app=\"$workload\",kubernetes_namespace=\"$namespace\",code!=\"OK\"}[$summarize]))by(code,method)",
     "legendFormat": "{{code}} | {{method}}"
    }
   ]
  },
  {
   "title": "gRPC 客户端 QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ego_client_handle_seconds_count{type=\"unary\",app=\"$workload\",kubernetes_namespace=\"$namespace\"}[$summarize]))by(name,method)",
     "legendFormat": " {{name}}-{{method}}"
    }
   ]
  },
  {
   "title": "gRPC 客户端  P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99,irate(ego_client_handle_seconds_bucket{type=\"unary\",app=\"$workload\",kubernetes_namespace=\"$namespace\"}[$summarize])>0)*1000)by(name,method)"
    }
   ]
  }
 ]
}